###############
# DESCRIPTION #
###############

# python code to analyze activity.h5 files generated by meta-RL program


##############
# PARAMETERS #
##############

data_path = './saved_data/20180920_130605/activity/activity.h5'

#############
# LIBRARIES #
#############

import numpy as np
import pandas as pd


################
# DATA_LOADING #
################

hdf = pd.HDFStore(data_path)
df = pd.DataFrame(hdf['activity'])
hdf.close()
