###############
# DESCRIPTION #
###############

# python code to analyze tensorflow summary files generated by meta-RL program


##############
# PARAMETERS #
##############

#data_path = './saved_data/20180920_130605/summary'
data_path = '/home/atiroms/Documents/Dropbox/Schizophrenia_Model/saved_data/20180921_011111/summary'


#############
# LIBRARIES #
#############

import numpy as np
import pandas as pd
import tensorflow as tf
#import matplotlib.pyplot as plt
import plotly as py
import cufflinks as cf
import glob
import os


###################
# DATA EXTRACTION #
###################

data_paths = glob.glob(os.path.join(data_path, "*", "event*"))

for p in data_paths:
    for e in tf.train.summary_iterator(p):
        print("Extracting episode " + str(int(e.step)), end="\r")
        if e.step==0:
            colnames=['Simulation/Global Episode Count']+[v.tag for v in e.summary.value]
            df=pd.DataFrame(columns=colnames)
        data=[e.step]+[v.simple_value for v in e.summary.value]
        df.loc[int(e.step)]=data


###############
# DATA SAVING #
###############

colnames=df.columns.values
df.columns=list(range(df.shape[1]))
hdf=pd.HDFStore(data_path+'/summary.h5')
hdf.put('summary',df,format='table',append=False,data_columns=True)
hdf.put('colnames',colnames)
hdf.close()


################
# DATA LOADING #
################

hdf = pd.HDFStore(data_path+'/summary.h5')
df = pd.DataFrame(df['summary'])
hdf.close()


#################
# VISUALIZATION #
#################

#cf.set_config_file(offline=True, theme="white", offline_show_link=False)
#cf.go_offline()

#df.plot(x='Simulation/Global Episode Count', y='Performance/Reward')
#plt.show()

#df.iplot(kind="scatter", mode='markers', x='Simulation/Global Episode Count', y='Performance/Reward')


fig = df.iplot(kind="scatter",  asFigure=True,x='Simulation/Global Episode Count', y='Performance/Reward')
py.offline.plot(fig, filename='example_scatter')
