###############
# DESCRIPTION #
###############

# python code to analyze variable generated by meta-RL program


##############
# PARAMETERS #
##############

#data_path='/home/atiroms/Documents/GitHub/Schizophrenia_Model/Model_03/saved_data/20181001_234806/model'
data_path='/home/atiroms/Documents/GitHub/Schizophrenia_Model/Model_03/saved_data/20181002_004726/model'


#############
# LIBRARIES #
#############

import numpy as np
import pandas as pd


################
# DATA LOADING #
################

class Load():
    def __init__(self,data_path=data_path):
        print('Starting hdf5 file loading.')
        self.data_path=data_path
        hdf = pd.HDFStore(self.data_path+'/variable.h5')
        self.output = pd.DataFrame(hdf['variable'])
        hdf.close()
        print('Finished hdf5 file loading.')


print('End of file.')